# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Parent', models.BooleanField()),
                ('Leader', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Clubbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICEContactName', models.CharField(max_length=200)),
                ('ICEContactPhone', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='clubbers',
            name='Family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Family'),
        ),
        migrations.AddField(
            model_name='adults',
            name='Family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Family'),
        ),
    ]
