# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20170620_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='group',
        ),
        migrations.AlterField(
            model_name='child',
            name='grade',
            field=models.IntegerField(choices=[(-1, 'P-Preschool'), (0, 'K-Kindergarten'), (1, '1-First'), (2, '2-Second'), (3, '3-Third'), (4, '4-Fourth'), (5, '5-Fifth'), (6, '6-Sixth')]),
        ),
        migrations.AlterField(
            model_name='child',
            name='photo_release',
            field=models.NullBooleanField(help_text='Unknown: Release not received - Yes/No: Release status'),
        ),
    ]
