# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20170621_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='club.Group'),
            preserve_default=False,
        ),
    ]
