# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What should this club be called?', max_length=20)),
                ('club', models.CharField(choices=[('A', 'Awanas'), ('P', 'Puggles'), ('C', 'Cubbies'), ('S', 'Sparks'), ('T', 'Truth & Training')], default='A', max_length=1)),
                ('age', models.CharField(help_text='Age range for this group.', max_length=10)),
                ('grades', models.CharField(help_text='Grades included in this group.', max_length=5)),
                ('leaders', models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
