# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grades',
            field=models.CharField(help_text='Grades included in this group.', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
